### ISSUE TITLE
Missing FLAs

### ISSUE THREAD

**Issue by FuseIsHere813** [Yoshubs/Hypnos-Lullaby#6]
No FLA files were found for Lullaby GF and other characters in the mod.

Did the FLAs get lost or something?

**Comment by CheesecakeForever** [comment]
They aren't lost, though i had trouble finding them too. Here: https://drive.google.com/file/d/10Z4rIh0K76snS3D_37YyWf8NXBwLy24l/view
This includes not only the .fla but other stuff.
